"""
MatchGuard - notify-function (serverless)
------------------------------------------
This is the one serverless piece required by the project brief. It is an
Azure Function (Python v2 programming model, same host.json/local.settings
layout we used in Lab Session 06's Blob Storage exercise).

What it does: scan-service POSTs a finished scan verdict here, the function
renders a short "verification certificate" and writes it straight into the
'certificates' container in Blob Storage, then hands back the blob URL.
Doing this in a function instead of inside scan-service means the
certificate-generation logic scales independently and to zero when nobody
is running a tournament - which is the whole point of serverless.

Author: Elias
"""

import datetime
import json
import logging
import os

import azure.functions as func
from azure.storage.blob import BlobServiceClient

app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

CONNECTION_STRING = os.environ.get("AZURE_STORAGE_CONNECTION_STRING", "")
CERTIFICATE_CONTAINER = os.environ.get("CERTIFICATE_CONTAINER_NAME", "certificates")


def _render_certificate(payload: dict) -> str:
    return (
        "MATCHGUARD VERIFICATION CERTIFICATE\n"
        "------------------------------------\n"
        f"Scan ID       : {payload.get('scan_id')}\n"
        f"Player        : {payload.get('gamertag')}\n"
        f"Tournament ID : {payload.get('tournament_id')}\n"
        f"Verdict       : {str(payload.get('verdict', '')).upper()}\n"
        f"File SHA-256  : {payload.get('sha256')}\n"
        f"Issued at     : {payload.get('created_at')}\n"
        f"Generated by  : notify-function (Azure Functions, serverless)\n"
        f"Function run  : {datetime.datetime.utcnow().isoformat()}Z\n"
    )


@app.function_name(name="notify")
@app.route(route="notify", methods=["POST"])
def notify(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("notify-function triggered - generating verification certificate")

    try:
        payload = req.get_json()
    except ValueError:
        return func.HttpResponse(json.dumps({"error": "expected a JSON body"}), status_code=400, mimetype="application/json")

    required = ["scan_id", "verdict"]
    missing = [k for k in required if k not in payload]
    if missing:
        return func.HttpResponse(
            json.dumps({"error": f"missing fields: {', '.join(missing)}"}), status_code=400, mimetype="application/json"
        )

    certificate_text = _render_certificate(payload)
    blob_name = f"{payload['scan_id']}.txt"

    if not CONNECTION_STRING:
        logging.warning("AZURE_STORAGE_CONNECTION_STRING not set - returning certificate text without uploading")
        return func.HttpResponse(
            json.dumps({"certificate_url": None, "certificate_text": certificate_text}),
            status_code=200,
            mimetype="application/json",
        )

    client = BlobServiceClient.from_connection_string(CONNECTION_STRING)
    try:
        client.create_container(CERTIFICATE_CONTAINER)
    except Exception:
        pass  # already exists

    blob_client = client.get_blob_client(container=CERTIFICATE_CONTAINER, blob=blob_name)
    blob_client.upload_blob(certificate_text.encode("utf-8"), overwrite=True)

    return func.HttpResponse(
        json.dumps({"certificate_url": blob_client.url}), status_code=200, mimetype="application/json"
    )
